sudo: false
language: node_js
node_js:
    - "0.12"
    - iojs

before_install:
  - wget -O vault.zip -q https://dl.bintray.com/mitchellh/vault/vault_0.1.2_linux_amd64.zip
  - unzip vault.zip
  - mkdir ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"
  - ~/bin/vault server -dev &
  - printf "export VAULT_TOKEN='`vault token create`'" >> .env

script:
  - npm run test-travis
