sudo: false
dist: trusty
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
before_install:
  - npm install json
  - curl -o vault.zip https://releases.hashicorp.com/vault/0.6.5/vault_0.6.5_linux_amd64.zip
  - unzip vault.zip
  - mkdir ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"
  - ~/bin/vault server -dev &
  - export VAULT_ADDR='http://127.0.0.1:8200' && T=`vault token-create -format=json | json auth.client_token` && printf "VAULT_TOKEN=\'$T'\n" >> .env

script:
  - npm run travis
