sudo: false
language: node_js
node_js:
    - iojs
    - node

before_install:
  - wget -O vault.zip -q https://dl.bintray.com/mitchellh/vault/vault_0.2.0_linux_amd64.zip
  - unzip vault.zip
  - mkdir ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"
  - ~/bin/vault server -dev &
  - export VAULT_ADDR='http://127.0.0.1:8200' && T=`vault token-create` && printf "VAULT_TOKEN=\'$T'\n" >> .env

script:
  - npm run travis
