sudo: false
language: node_js
node_js:
  - "4.*"
  - "5.*"
before_install:
  - npm install json
  - wget -O vault.zip -q https://releases.hashicorp.com/vault/0.5.0/vault_0.5.0_linux_amd64.zip
  - unzip vault.zip
  - mkdir ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"
  - ~/bin/vault server -dev &
  - export VAULT_ADDR='http://127.0.0.1:8200' && T=`vault token-create -format=json | json auth.client_token` && printf "VAULT_TOKEN=\'$T'\n" >> .env

script:
  - npm run travis
