language: node_js
node_js:
    - "0.10"
    - "0.12"
    - iojs

before_install:
    - wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
    - sudo dpkg -i influxdb_latest_amd64.deb
    - sudo /etc/init.d/influxdb start

script:
  - npm run test-travis
